development:
  dialect: "pg"
  url: postgres://yannickchiasson:@localhost:5432/noonde_api_server_development?sslmode=disable
development_writer:
  dialect: "pg"
  url: postgres://apiserver_w:@localhost:5432/noonde_api_server_development?sslmode=disable
development_reader:
  dialect: "pg"
  url: postgres://apiserver_r:@localhost:5432/noonde_api_server_development?sslmode=disable
test:
  dialect: "pg"
  url: postgres://yannickchiasson:@localhost:5432/noonde_api_server_test?sslmode=disable
test_writer:
  dialect: "pg"
  url: postgres://apiserver_w:@localhost:5432/noonde_api_server_test?sslmode=disable
test_reader:
  dialect: "pg"
  url: postgres://apiserver_r:@localhost:5432/noonde_api_server_test?sslmode=disable
production:
  dialect: "pg"
  database: "noonde_api_server_production"
  host: {{envOr "DATABASE_HOST" "localhost"}}
  port: {{envOr "DATABASE_PORT" "3306"}}
  user: {{envOr "DATABASE_USER" "root"}}
  password: {{envOr "DATABASE_PASSWORD" "root"}}
  #
  # And you can also override connection parameters by setting it under options.
  #
  #options:
  #  parseTime: true
  #  multiStatements: true
  #  readTimeout: 3s
  #  encoding: "utf8mb4_general_ci"
  #
  # CAUTION!
  #   `parseTime` and` multiStatements` must be set to `true` to work properly.
  #   If you are not sure, do not change (or set) these values.
