#!/usr/bin/env bash

#
# USAGE
#
# ./bin/create_migration add_column_to_table

initial_directory=$(pwd)
cd "$(dirname "$0")"

../tools/migrate create -ext sql -dir ./migrations $@

cd $initial_directory
